!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
!
FUNCTION PT_CD(params) RESULT (PT)
  USE COMMON_D
  IMPLICIT NONE
  REAL, INTENT(IN) :: params(3), c_hist(y), i_hist(y), y
  REAL :: b(y), q
  INTEGER :: yi
  REAL :: r
  INTRINSIC EXP
  INTEGER :: k
  REAL :: p
  INTRINSIC SUM
  REAL :: pwx1
  REAL :: pwr1
  REAL, DIMENSION(y) :: arg1
  REAL :: pt
  r = EXP(params(1))
  k = EXP(params(2))
  p = EXP(params(3))
  b(1) = k
  DO yi=2,y
    pwx1 = b(yi-1)/k
    pwr1 = pwx1**p
    b(yi) = b(yi-1) + r*b(yi-1)/p*(1.0-pwr1) - c_hist(yi-1)
  END DO
  q = SUM(i_hist)/SUM(b)
  arg1(:) = (q*b-i_hist)**2
  pt = SUM(arg1(:))
  RETURN
END FUNCTION PT_CD
