1 Command: Command-line option -vars is deprecated: please use -head instead
2 File: cygwin warning:
3 File:   MS-DOS style path detected: C:\Users\jum002\Documents\GitHub\niMSE-IO-BET-YFT\Rscripts\pt.f95
4 File:   Preferred POSIX equivalent is: /cygdrive/c/Users/jum002/Documents/GitHub/niMSE-IO-BET-YFT/Rscripts/pt.f95
5 File:   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
6 File:   Consult the user's guide for more details about POSIX paths:
7 File:     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
8 pt: (TC16) Type mismatch in assignment: INTEGER receives REAL
9 pt: (TC07) Loop bound is expected to be integer, and is here REAL
10 pt: (DF03) variable y is used before initialized
11 pt: (DF03) variable y is used before initialized
12 pt: (DF03) variable y is used before initialized
13 pt: (DF03) variable y is used before initialized
14 pt: (DF03) variable c_hist[yi-1] is used before initialized
15 pt: (DF03) variable i_hist is used before initialized
